### ISSUE TITLE
Implement interface to adjust application settings

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#52]
Possible application settings:

* [ ] Do unique keys apply across the entire site or only intra-lab
* [ ] Do users get to see all submitted data or only intra-lab
* [ ] Accent color of the page
* [x] HTML to replace the current "DataMeta" logo with (branding)
* [ ] Submission agreement that has to be confirmed by every user before data can be submitted (e.g. no personal data, etc)

**Comment by KerstenBreuer** [comment]
I am just thinking, the general configurations (like which metadata fields are available) just need to be specified once in the lifetime of a DataMeta instance to define its purpose, right? If yes, wouldn't it be sufficient to configure this in a simple yaml config before the application is launching. Since this is done by an admin and not the user, I think a UI is not needed.

Something simple like:
```
metadata_fields:
    - fastq_file:
        regexp: .*\.fastq
        mandatory: true
        isfile: yes
        order: 1
    - sequencing_data:
        ...

# maybe also include here other global setting like:
port: 8443
useOIDC: false
....
```
